# Generated by Django 5.1.4 on 2026-04-22 17:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('visitor_name', models.CharField(max_length=120)),
                ('visitor_phone', models.CharField(db_index=True, max_length=30)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_company', models.CharField(blank=True, max_length=120)),
                ('visitor_id_type', models.CharField(blank=True, max_length=50)),
                ('visitor_id_no', models.CharField(blank=True, max_length=80)),
                ('purpose_of_visit', models.CharField(max_length=255)),
                ('host_name', models.CharField(db_index=True, max_length=120)),
                ('host_department', models.CharField(blank=True, max_length=120)),
                ('host_phone', models.CharField(blank=True, max_length=30)),
                ('host_email', models.EmailField(blank=True, max_length=254)),
                ('visit_date', models.DateField(db_index=True)),
                ('visit_time', models.TimeField()),
                ('qr_token', models.CharField(db_index=True, max_length=96, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CHECKED_IN', 'Checked-in'), ('CHECKED_OUT', 'Checked-out')], db_index=True, default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_visits', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CHECK_IN', 'Checked in'), ('CHECK_OUT', 'Checked out')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='visitors.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['reference_no'], name='visitors_vi_referen_cc8eef_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['qr_token'], name='visitors_vi_qr_toke_ff0706_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='visitors_vi_status_1b35dd_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_date'], name='visitors_vi_visit_d_a3dfd8_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visitor_phone'], name='visitors_vi_visitor_d8cca1_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['host_name'], name='visitors_vi_host_na_4d28f6_idx'),
        ),
    ]
